# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c67ebe8afc392c15fa8c710995461d13ab49aad4e15c51309f5b912a78155f35c81ca93e70649cc6b66140d5073d348805a94ed5538dd1086f92db02b7f41c27

test:
  secret_key_base: 99d3294a2de0521f823537ce8c17f747d89d8301f250943248f4e207645b40bfd7df70e0d1cb3a471ee7ea71f5e1f0f9a681f9fbe10f2445752b81fd700e3cc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
